apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dcjewelry-prometheus
rules:
  - apiGroups: [""]
    resources:
      - nodes
      - nodes/metrics
      - nodes/proxy
      - services
      - endpoints
      - pods
    verbs: ["get", "list", "watch"]
  - nonResourceURLs:
      - /metrics
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dcjewelry-prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dcjewelry-prometheus
subjects:
  - kind: ServiceAccount
    name: prometheus
    namespace: monitoring
