apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - path: ingress-patch.yaml
images:
  - name: ghcr.io/your-github-user/dcjewelry-backend
    newName: ghcr.io/your-github-user/dcjewelry-backend
    newTag: latest
  - name: ghcr.io/your-github-user/dcjewelry-frontend
    newName: ghcr.io/your-github-user/dcjewelry-frontend
    newTag: latest
