apiVersion: v1
kind: Service
metadata:
  name: dcjewelry-backend
  namespace: dcjewelry
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: dcjewelry-backend
  ports:
    - name: http
      port: 80
      targetPort: http
