apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dcjewelry
  namespace: dcjewelry
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
spec:
  ingressClassName: traefik
  rules:
    - host: dcjewelry.example.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: dcjewelry-backend
                port:
                  name: http
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dcjewelry-frontend
                port:
                  name: http
